# Generated by Django 2.2.12 on 2020-09-27 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_user_profile',
        ),
    ]
